use_frameworks!

platform :ios, '10.0'

target 'dynamicFramework_Example' do
  pod 'dynamicFramework', :path => '../'

  target 'dynamicFramework_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
